micronaut:
  application:
    name: keyManager

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${DATABASE_URI:`jdbc:postgresql://localhost:5432/keymanager`}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER:`user`}
    password: ${DATABASE_PASSWORD:`123456`}
    schema-generate: CREATE_DROP
    dialect: ${DATABASE_DIALECT:`POSTGRES`}

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

itau:
  client:
    url: ${ITAU_URL:`http://localhost:9091`}

bcb:
  client:
    url: ${BCB_URL:`http://localhost:8082`}