apiVersion: apps/v1
kind: Deployment
metadata:
  name: itau-client-deployment
spec:
  selector:
    matchLabels:
      app: itau-client
  template:
    metadata:
      name: itau-client-deployment
      labels:
        app: itau-client
        client: client
    spec:
      containers:
        - name: itau-client-container
          image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
          ports:
            - name: itau-port
              containerPort: 9091
              protocol: TCP